# Generated by Django 2.2.4 on 2019-09-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chdb_app', '0002_remove_event_fuckoff'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='at_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chdb_app.Location'),
        ),
    ]
