# Generated by Django 2.2.4 on 2019-09-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chdb_app', '0003_event_at_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basetransition',
            name='caused_by_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_transitions', to='chdb_app.BaseTransition'),
        ),
        migrations.AlterField(
            model_name='basetransition',
            name='caused_by_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_transitions', to='chdb_app.Event'),
        ),
        migrations.AlterField(
            model_name='basetransition',
            name='caused_by_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_transitions', to='chdb_app.Group'),
        ),
        migrations.AlterField(
            model_name='basetransition',
            name='caused_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_transitions', to='chdb_app.Person'),
        ),
        migrations.AlterField(
            model_name='basetransition',
            name='change_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_here', to='chdb_app.Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='at_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='chdb_app.Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chdb_app.Event'),
        ),
        migrations.AlterField(
            model_name='fieldchange',
            name='caused_by_change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_changes', to='chdb_app.FieldChange'),
        ),
        migrations.AlterField(
            model_name='fieldchange',
            name='caused_by_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_changes', to='chdb_app.Event'),
        ),
        migrations.AlterField(
            model_name='fieldchange',
            name='caused_by_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_changes', to='chdb_app.Group'),
        ),
        migrations.AlterField(
            model_name='fieldchange',
            name='caused_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caused_changes', to='chdb_app.Person'),
        ),
        migrations.AlterField(
            model_name='fieldchange',
            name='change_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_here', to='chdb_app.Location'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_created_at', to='chdb_app.Location'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to='chdb_app.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to='chdb_app.Person'),
        ),
        migrations.AlterField(
            model_name='groupatlocation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupatlocation',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupatlocation',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupeventparticipation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupeventparticipation',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupeventparticipation',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grouphierarchyposition',
            name='ordinal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='hierarchy_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chdb_app.GroupHierarchyPosition'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chdb_app.Location'),
        ),
        migrations.AlterField(
            model_name='metagroupmembership',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metagroupmembership',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='metagroupmembership',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='born_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='births', to='chdb_app.Location'),
        ),
        migrations.AlterField(
            model_name='personatlocation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personatlocation',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personatlocation',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personeventparticipation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personeventparticipation',
            name='date_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personeventparticipation',
            name='date_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
