# Generated by Django 2.2.4 on 2019-09-03 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chdb_app', '0004_auto_20190902_1632'),
    ]

    operations = [
        migrations.CreateModel(
            name='Army',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chdb_app.Group')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('chdb_app.group',),
        ),
    ]
